### ISSUE TITLE
when change my picture occurrred TypeError: 'module' object is not callable

### ISSUE THREAD

**Issue by Simwake** [KohakuBlueleaf/PixelOE#4]
C:\Users\administrator>pixeloe.pixelize img/test.png --output_img img/test2.png --target_size 256 --patch_size 8
Traceback (most recent call last):
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 196, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "C:\Users\Administrator\AppData\Local\Programs\Python\Python310\lib\runpy.py", line 86, in _run_code
    exec(code, run_globals)
  File "C:\Users\zyx\AppData\Roaming\Python\Python310\Scripts\pixeloe.pixelize.exe\__main__.py", line 7, in <module>
  File "C:\Users\zyx\AppData\Roaming\Python\Python310\site-packages\pixeloe\cli.py", line 39, in pixelize
    img = pixelize(
TypeError: 'module' object is not callable

**Comment by KohakuBlueleaf** [comment]
Fixed in 0.0.10
